### ISSUE TITLE
Message if no output produced

### ISSUE THREAD

**Issue by HaleTom** [tris203/hawtkeys.nvim#64]
I ran `HawkeysDups` and got the following:

![image](https://github.com/tris203/hawtkeys.nvim/assets/13854417/4012cde2-e799-49e6-990a-4cdef193d090)

I'm not sure if this means there's no dupes or if somthign didn't work properly.

Would you consider a message if there are no dupes / or if the output of the command is indeed empty, eg:

`--- Command succeeded with empty output ---`

**Comment by tris203** [comment]
Great idea,  I have added a PR for this.

![image](https://github.com/tris203/hawtkeys.nvim/assets/18444302/648a069b-d1e3-49f6-9847-d2525d23936b)

**Comment by HaleTom** [comment]
Awesome, thanks @tris203 !
