### ISSUE TITLE
Escape paths before matching with lua patterns

### ISSUE THREAD

**Issue by willothy** [tris203/hawtkeys.nvim#70]
As seen in #67, paths containing % and other symbols can cause issues with lua patterns - we should escape or validate paths before matching against them.

**Comment by tris203** [comment]
Should we just go back to using ```vim.fn.stdpath("config")``` to get the path? 

The only other directory we would need to consider is after

**Comment by willothy** [comment]
> Should we just go back to using `vim.fn.stdpath("config")` to get the path?
> 
> The only other directory we would need to consider is after

hmm that may be a good idea, but lets look into the issue more before we decide - not sure if that will be needed if we escape everything properly.
