### ISSUE TITLE
Why nvim-treesitter is a dependency?

### ISSUE THREAD

**Issue by gukz** [tris203/hawtkeys.nvim#83]
I do not install nvim-treesitter, and when I install this plugin, I hit below error:

E5108: Error executing lua ...ev/nvim/nvim-data/lazy/hawtkeys.nvim/lua/hawtkeys/ts.lua:6: module 'nvim-treesitter.compat' not
found:
        no field package.preload['nvim-treesitter.compat']
cache_loader: module nvim-treesitter.compat not found
cache_loader_lib: module nvim-treesitter.compat not found
        no file '.\nvim-treesitter\compat.lua'
        no file 'C:\Program Files\Neovim\bin\lua\nvim-treesitter\compat.lua'
        no file 'C:\Program Files\Neovim\bin\lua\nvim-treesitter\compat\init.lua'
        no file '.\nvim-treesitter\compat.dll'
        no file 'C:\Program Files\Neovim\bin\nvim-treesitter\compat.dll'
        no file 'C:\Program Files\Neovim\bin\loadall.dll'
        no file '.\nvim-treesitter.dll'
        no file 'C:\Program Files\Neovim\bin\nvim-treesitter.dll'
        no file 'C:\Program Files\Neovim\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        ...ev/nvim/nvim-data/lazy/hawtkeys.nvim/lua/hawtkeys/ts.lua:6: in main chunk
        [C]: in function 'require'
        ...nvim/nvim-data/lazy/hawtkeys.nvim/lua/hawtkeys/score.lua:3: in main chunk
        [C]: in function 'require'
        ...ev/nvim/nvim-data/lazy/hawtkeys.nvim/lua/hawtkeys/ui.lua:3: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk

:version

NVIM v0.10.0-dev-1746+g5651c1ff2
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
Run ":verbose version" for more info

**Comment by tris203** [comment]
Treesitter is used to read your config files. I need to update the documentation to specify the dependency

Additionally, it appears your on windows. windows support is experimental at the moment on the crossplatform_tests branch

I have done some testing with it, but don't use windows that often
