### ISSUE TITLE
Version issue: nvim_get_hl is nil

### ISSUE THREAD

**Issue by Huluk** [tris203/hawtkeys.nvim#86]
On my neovim instance (version 0.7.2, I know it's outdated but that's what I'm stuck with for now) hawtkeys fails with
`.nvim/lua/hawtkeys/init.lua:75: attempt to call field 'nvim_get_hl' (a nil value)`.

Could you specify the minimum neovim version which is needed for this plugin? Maybe as a message on startup, or simply in the readme.

**Comment by tris203** [comment]
Hi Huluk,

Its here in the docs

https://github.com/tris203/hawtkeys.nvim/blob/8bce74ca1de05554f031849482bccec42e9a16a0/doc/hawtkeys.txt#L1

**Comment by Huluk** [comment]
Thank you, Tristan!

The doc feels like the manual I'd read after installing, to configure it correctly. The readme is the one people read before installing, so the requirements would be more visible there.

In any case, thank you for your work on this plugin!

**Comment by tris203** [comment]
I have created a PR to add the min version to the README.

on a side note, I would really recommend updating to at least 0.9.x if you can!

**Comment by Huluk** [comment]
Awesome, thank you!

I updated at home, but at work I'm tied to the [Debian releases](https://qa.debian.org/cgi-bin/watch?pkg=neovim) unless I want to put a lot of work into it. 0.9.5 is already in the update queue there, I'll give it a month :)
