### ISSUE TITLE
"Not an editor command" - no commands available

### ISSUE THREAD

**Issue by wilfredjonathanjames** [tris203/hawtkeys.nvim#92]
Hi there,

I've installed Hawtkeys with packer:
```lua
    use({
        "tris203/hawtkeys.nvim",
        requires = {"nvim-lua/plenary.nvim", "nvim-treesitter/nvim-treesitter"}
    })
```

And no hawtkeys commands are available.

![image](https://github.com/user-attachments/assets/62f187b0-3a09-4697-ac90-e939c09f9ff0)

No install failures, not other errors. Both dependencies were already installed.

```
macos@14.7
nvim@0.10.2
```

**Comment by tris203** [comment]
I dont know anything about Packer, but you will need to run the setup() function to have the commands available

**Comment by wijonja** [comment]
Ah I should have known. And it requires a table is that correct? I'll leave this for anyone else that ends up here.

```lua
require('hawtkeys').setup({})
```
